Document required Emscripten version
Task `./gradlew :publishToMavenLocal` runs another task called
`:linkWasmWithES6`. When using current latest emsdk v4.0.6,
`:linkWasmWithES6` fails with the following error messages:

```
error: undefined symbol: saveSetjmp(referenced by root reference
(e.g. compiled C/C++ code)) undefined symbol: saveSetjmp(referenced by
root reference (e.g. compiled C/C++ code))
...
error: undefined symbol: testSetjmp (referenced by root reference
(e.g. compiled C/C++ code)) undefined symbol: testSetjmp (referenced by
root reference (e.g. compiled C/C++ code))
```

I assume that the issue lies in different compiler versions used for the
project and its dependencies. This seems to be true, because changing
from v4.0.6 to v3.1.56 fixes the errors.